backend:
  name: git-gateway
  repo: lanesgood/snow-cave
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'work'
    label: 'Work'
    folder: 'content/work'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Year', name: 'year', widget: 'datetime' }
      - { label: 'Role', name: 'role', widget: 'string' }
      - { label: 'Site', name: 'site', widget: 'string' }
      - { label: 'For', name: 'for', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }